### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by skyGtm** [89z/rosso#1] opened 2021-09-26 16:22 UTC
Hello I came here from NewPipe,

I was able to install the extension in Firefox Nightly. But cannot make it work.
1. I clicked Extension icon. which opened new tab.
2. In other tabs, I right clicked Youtube videos which creates a browser popup but the video is not added to the playlist as mentioned in Readme.md

Does just right clicking works?
Am I doing something wrong?

**Comment by skyGtm** [comment] 2021-09-26 16:27
It would be better if there was proper Instruction/Video in `Readme.md`

**Comment by 89z** [comment] 2021-09-26 16:28
Hello, yes I can try to fix this.

Can you clarify, what page you are right clicking from?

**Comment by skyGtm** [comment] 2021-09-26 16:41
I tried right clicking from Youtube home and Youtube search

https://user-images.githubusercontent.com/50160188/134816326-8595627f-678a-4394-96ec-01cd908ada24.mp4

**Comment by 89z** [comment] 2021-09-26 16:53
I see. The issue seems to be here:

https://github.com/89z/rosso/blob/0f1241b536fa945864fa8e5e623074df9e13cb13/youtube.js#L41

as YouTube links on YouTube pages omit the origin:

~~~html
<a id="video-title-link" class="yt-simple-endpoint style-scope
ytd-rich-grid-media" aria-label="when older people name drop during a
conversation and expect you to know who it is by abelina sabrina 2 years ago 20
seconds 209,622 views" title="when older people name drop during a conversation
and expect you to know who it is" href="/watch?v=Qkce8-77n2Q">
~~~

so I will just need to match all link elements, then filter on right click based on one of these attributes:

~~~
baseURI: "https://www.youtube.com/"
host: "www.youtube.com"
hostname: "www.youtube.com"
href: "https://www.youtube.com/watch?v=Qkce8-77n2Q"
origin: "https://www.youtube.com"
~~~

I will try to work up a fix today, as well as better documentation.

**Comment by 89z** [comment] 2021-09-26 18:22
This should be fixed now

**Comment by skyGtm** [comment] 2021-09-27 01:44
Thank you.
This is now working as expected.

But I experiencing new bug:
Steps to reproduce:
1. Add few items to the list. (by right clicking youtube videos)
2. wait for about 1 minute.
3. Again try to right click youtube videos, these new videos are not added to the playlist

**Comment by 89z** [comment] 2021-09-27 01:51
I cannot reproduce this, but I think I know the problem. The code currently looks for links for 10 seconds:

https://github.com/89z/rosso/blob/6a930cf6a34275a25a2f51af1cac23439edeeb15/delay.js#L3-L4

So any links that are added after 10 seconds, will not be recognized by the extension. Can you again clarify which page you are using for this purpose? I might be able to fix the problem.

**Comment by 89z** [comment] 2021-09-29 03:21
closing issue since no response

**Closed by 89z** 2021-09-29 03:21 UTC
